development:
  metrics: ["sentiment","problem","suggestion"]
  sentiment:  true
  problem:  true
  suggestion: true
production:
  metrics: ["sentiment","problem","suggestion"]
  sentiment:  true
  problem:  true
  suggestion: true
test:
  metrics: ["sentiment","problem","suggestion"]
  sentiment:  true
  problem:  true
  suggestion: true