development:
  :credentials: !ruby/object:Credentials
    actions:
      content_pages:
        view_default: true
        view: true
        list: false
      roles:
        list: false
      permissions:
        list: false
      auth:
        login: true
        logout: true
        login_failed: true
      menu_items:
        link: true
        list: false
      site_controllers:
        list: false
      controller_actions:
        list: false
      system_settings:
        list: false
      users:
        list: false
        keys: true
      admin:
        list_instructors: false
        list_administrators: false
        list_super_administrators: false
      course:
        list_folders: false
        add_ta: false
        destroy_course: false
        edit_course: false
        new_course: false
        new_folder: false
        remove_ta: false
        update_course: false
        view_teaching_assistants: false
        create_course: false
        list: false
      suggestion:
        create: true
        new: true
      questionnaire:
        list: false
        create_questionnaire: false
        edit_questionnaire: false
        copy_questionnaire: false
        save_questionnaire: false
        new_quiz: true
        create_quiz_questionnaire: true
        update_quiz: true
        edit_quiz: true
        view_quiz: true
      participants:
        add_student: false
        edit_team_members: false
        list_students: false
        list_courses: false
        list_assignments: false
        change_handle: true
      assignment:
        list: false
      institution:
        list: false
      student_task:
        list: true
      profile:
        edit: true
      team:
        list: false
        list_assignments: false
      teams_users:
        list: false
      impersonate:
        start: false
        impersonate: true
      review_mapping:
        list: false
        assign_reviewer_dynamically: true
        release_reservation: true
        show_available_submissions: true
        assign_metareviewer_dynamically: true
        add_self_reviewer: true
        assign_quiz_dynamically: true
      tree_display:
        list: false
        drill: false
        goto_questionnaires: false
        goto_author_feedbacks: false
        goto_review_rubrics: false
        goto_courses: false
        goto_assignments: false
        goto_teammate_reviews: false
        goto_metareview_rubrics: false
        goto_teammatereview_rubrics: false
      grades:
        view_my_scores: true
      sign_up_sheet:
        signup_topics: true
        signup: true
        delete_signup: true
        team_details: true
      review_files:
        show_code_file: true
        show_code_file_diff: true
        show_all_submitted_files: true
        submit_comment: true
        submit_review_file: true
      popup:
        automated_metareview_details_popup: true
      advice:
        edit_advice: false
        save_advice: false
      response:
        delete: false
      analytic:
        assignment_list: false
        course_list: false
        get_graph_data_bundle: false
        graph_data_type_list: false
        index: false
        init: false
        render_sample: false
        team_list: false
      advertise_for_partner:
        remove: true
      versions:
        revert: true
    controllers:
      content_pages: false
      controller_actions: false
      auth: false
      markup_styles: false
      menu_items: false
      permissions: false
      roles: false
      site_controllers: false
      system_settings: false
      users: true
      roles_permissions: false
      admin: false
      course: false
      assignment: false
      questionnaire: false
      participants: false
      reports: true
      institution: false
      student_task: true
      profile: true
      team: false
      teams_users: false
      import_file: false
      participant_choices: false
      impersonate: false
      review_mapping: false
      grades: false
      tree_display: false
      student_team: true
      invitation: true
      password_retrieval: true
      submitted_content: true
      eula: true
      student_review: true
      publishing: true
      export_file: false
      response: true
      popup: false
      sign_up_sheet: false
      suggestion: false
      delete_object: false
      assessment360: false
      review_files: true
      advertise_for_partners: true
      join_team_requests: true
      advertise_for_partner: true
      automated_metareviews: true
      advice: false
      analytic: false
      versions: true
      student_quiz: true
    pages:
      home: true
      expired: true
      notfound: true
      denied: true
      contact_us: true
      site_admin: false
      adminpage: false
      credits: true
      wiki: true
    permission_ids:
    - 8
    - 4
    - 3
    role_id: 1
    role_ids:
    - 1
    updated_at: 2015-06-11 15:23:43.000000000 Z
  :menu: !ruby/object:Menu
    by_id:
      1: &1 !ruby/object:Menu::Node
        content_page_id: 1
        controller_action_id:
        id: 1
        label: Home
        name: home
        parent:
        parent_id:
        site_controller_id:
        url: "/home"
      26: &2 !ruby/object:Menu::Node
        content_page_id:
        controller_action_id: 33
        id: 26
        label: Assignments
        name: student_task
        parent:
        parent_id:
        site_controller_id: 23
        url: "/student_task/list"
      27: &4 !ruby/object:Menu::Node
        content_page_id:
        controller_action_id: 36
        id: 27
        label: Profile
        name: profile
        parent:
        parent_id:
        site_controller_id: 26
        url: "/profile/edit"
      2: &5 !ruby/object:Menu::Node
        content_page_id: 6
        controller_action_id:
        id: 2
        label: Contact Us
        name: contact_us
        parent:
        parent_id:
        site_controller_id:
        url: "/contact_us"
        children:
        - 14
      14: &7 !ruby/object:Menu::Node
        content_page_id: 10
        controller_action_id:
        id: 14
        label: Credits &amp; Licence
        name: credits
        parent:
        parent_id: 2
        site_controller_id:
        url: "/credits"
      50: &24 !ruby/object:Menu::Node
        content_page_id:
        controller_action_id: 15
        id: 50
        label: Anonymized view
        name: anonymized_view
        parent:
        parent_id: 37
        site_controller_id: 35
        url: "/users/set_anonymized_view"
    by_name:
      home: *1
      student_task: *2
      profile: *4
      contact_us: *5
      credits: *7
      anonymized_view: *24
    crumbs:
    - 1
    root: &8 !ruby/object:Menu::Node
      parent:
      children:
      - 1
      - 26
      - 27
      - 2
      - 50
    selected:
      1: *1
    vector:
    - *8
    - *1
test:
  :credentials: !ruby/object:Credentials
    role_id: 1
    updated_at: 2014-12-15 21:30:58.000000000 Z
    role_ids:
    - 1
    permission_ids:
    - 6
    - 3
    - 2
    actions:
      content_pages:
        view_default: true
        view: true
        list: false
      controller_actions:
        list: false
      auth:
        login: true
        logout: true
        login_failed: true
      menu_items:
        link: true
        list: false
      permissions:
        list: false
      roles:
        list: false
      site_controllers:
        list: false
      system_settings:
        list: false
      users:
        list: false
        keys: true
      admin:
        list_instructors: false
        list_administrators: false
        list_super_administrators: false
      course:
        list_folders: false
      assignment:
        list: false
      questionnaire:
        list: false
        create_questionnaire: false
        edit_questionnaire: false
        copy_questionnaire: false
        save_questionnaire: false
      participants:
        add_student: false
        edit_team_members: false
        list_students: false
        list_courses: false
        list_assignments: false
        change_handle: true
      institution:
        list: false
      student_task:
        list: true
      profile:
        edit: true
      team:
        list: false
        list_assignments: false
      teams_users:
        list: false
      impersonate:
        start: false
        impersonate: true
      review_mapping:
        list: false
        add_dynamic_reviewer: true
        release_reservation: true
        show_available_submissions: true
        assign_reviewer_dynamically: true
        assign_metareviewer_dynamically: true
      grades:
        view_my_scores: true
      tree_display:
        list: false
        drill: false
        goto_questionnaires: false
        goto_author_feedbacks: false
        goto_review_rubrics: false
        goto_courses: false
        goto_assignments: false
        goto_teammate_reviews: false
        goto_metareview_rubrics: false
        goto_teammatereview_rubrics: false
      sign_up_sheet:
        list: true
        signup: true
        delete_signup: true
      suggestion:
        create: true
        new: true
      advice:
        edit_advice: false
        save_advice: false
      advertise_for_partner:
        add_advertise_comment: true
        edit: true
        new: true
        remove: true
        update: true
      join_team_requests:
        create: true
        decline: true
        destroy: true
        edit: true
        index: true
        new: true
        show: true
        update: true
    controllers:
      content_pages: false
      controller_actions: false
      auth: false
      markup_styles: false
      menu_items: false
      permissions: false
      roles: false
      site_controllers: false
      system_settings: false
      users: true
      roles_permissions: false
      admin: false
      course: false
      assignment: false
      questionnaire: false
      advice: false
      participants: false
      reports: true
      institution: false
      student_task: true
      profile: true
      team: false
      teams_users: false
      impersonate: false
      import_file: false
      review_mapping: false
      grades: false
      participant_choices: false
      tree_display: false
      student_team: true
      invitation: true
      password_retrieval: true
      submitted_content: true
      eula: true
      student_review: true
      publishing: true
      export_file: false
      response: true
      sign_up_sheet: false
      suggestion: false
      delete_object: false
      advertise_for_partner: true
      join_team_requests: true
    pages:
      home: true
      expired: true
      notfound: true
      denied: true
      contact_us: true
      site_admin: false
      admin: false
      credits: true
  :menu: !ruby/object:Menu
    root: &7 !ruby/object:Menu::Node
      parent:
      children:
      - 1
      - 5
      - 6
      - 7
      - 50
    by_id:
      1: &1 !ruby/object:Menu::Node
        parent:
        parent_id:
        name: home
        id: 1
        label: Home
        site_controller_id:
        controller_action_id:
        content_page_id: 1
        url: "/home"
      5: &2 !ruby/object:Menu::Node
        parent:
        parent_id:
        name: student_task
        id: 5
        label: Assignments
        site_controller_id: 20
        controller_action_id: 33
        content_page_id:
        url: "/student_task/list"
      6: &3 !ruby/object:Menu::Node
        parent:
        parent_id:
        name: profile
        id: 6
        label: Profile
        site_controller_id: 21
        controller_action_id: 34
        content_page_id:
        url: "/profile/edit"
      7: &4 !ruby/object:Menu::Node
        parent:
        parent_id:
        name: contact_us
        id: 7
        label: Contact Us
        site_controller_id:
        controller_action_id:
        content_page_id: 5
        url: "/contact_us"
        children:
        - 9
      9: &6 !ruby/object:Menu::Node
        parent:
        parent_id: 7
        name: credits
        id: 9
        label: Credits &amp; Licence
        site_controller_id:
        controller_action_id:
        content_page_id: 8
        url: "/credits"
      50: &24 !ruby/object:Menu::Node
        content_page_id:
        controller_action_id: 15
        id: 50
        label: Anonymized view
        name: anonymized_view
        parent:
        parent_id: 37
        site_controller_id: 35
        url: "/users/set_anonymized_view"
    by_name:
      home: *1
      student_task: *2
      profile: *3
      contact_us: *4
      credits: *6
      anonymized_view: *24
    selected:
      1: *1
    vector:
    - *7
    - *1
    crumbs:
    - 1
production:
  :credentials: !ruby/object:Credentials
    actions:
      content_pages:
        view_default: true
        view: true
        list: false
      roles:
        list: false
      permissions:
        list: false
      auth:
        login: true
        logout: true
        login_failed: true
      menu_items:
        link: true
        list: false
      site_controllers:
        list: false
      controller_actions:
        list: false
      system_settings:
        list: false
      users:
        list: false
        keys: true
      admin:
        list_instructors: false
        list_administrators: false
        list_super_administrators: false
      course:
        list_folders: false
        add_ta: false
        destroy_course: false
        edit_course: false
        new_course: false
        new_folder: false
        remove_ta: false
        update_course: false
        view_teaching_assistants: false
        create_course: false
        list: false
      suggestion:
        create: true
        new: true
      questionnaire:
        list: false
        create_questionnaire: false
        edit_questionnaire: false
        copy_questionnaire: false
        save_questionnaire: false
        new_quiz: true
        create_quiz_questionnaire: true
        update_quiz: true
        edit_quiz: true
        view_quiz: true
      participants:
        add_student: false
        edit_team_members: false
        list_students: false
        list_courses: false
        list_assignments: false
        change_handle: true
      assignment:
        list: false
      institution:
        list: false
      student_task:
        list: true
      profile:
        edit: true
      team:
        list: false
        list_assignments: false
      teams_users:
        list: false
      impersonate:
        start: false
        impersonate: true
      review_mapping:
        list: false
        assign_reviewer_dynamically: true
        release_reservation: true
        show_available_submissions: true
        assign_metareviewer_dynamically: true
        add_self_reviewer: true
        assign_quiz_dynamically: true
      tree_display:
        list: false
        drill: false
        goto_questionnaires: false
        goto_author_feedbacks: false
        goto_review_rubrics: false
        goto_courses: false
        goto_assignments: false
        goto_teammate_reviews: false
        goto_metareview_rubrics: false
        goto_teammatereview_rubrics: false
      grades:
        view_my_scores: true
      sign_up_sheet:
        signup_topics: true
        signup: true
        delete_signup: true
        team_details: true
      review_files:
        show_code_file: true
        show_code_file_diff: true
        show_all_submitted_files: true
        submit_comment: true
        submit_review_file: true
      popup:
        automated_metareview_details_popup: true
      advice:
        edit_advice: false
        save_advice: false
      response:
        delete: false
      analytic:
        assignment_list: false
        course_list: false
        get_graph_data_bundle: false
        graph_data_type_list: false
        index: false
        init: false
        render_sample: false
        team_list: false
      advertise_for_partner:
        remove: true
      versions:
        revert: true
    controllers:
      content_pages: false
      controller_actions: false
      auth: false
      markup_styles: false
      menu_items: false
      permissions: false
      roles: false
      site_controllers: false
      system_settings: false
      users: true
      roles_permissions: false
      admin: false
      course: false
      assignment: false
      questionnaire: false
      participants: false
      reports: true
      institution: false
      student_task: true
      profile: true
      team: false
      teams_users: false
      import_file: false
      participant_choices: false
      impersonate: false
      review_mapping: false
      grades: false
      tree_display: false
      student_team: true
      invitation: true
      password_retrieval: true
      submitted_content: true
      eula: true
      student_review: true
      publishing: true
      export_file: false
      response: true
      popup: false
      sign_up_sheet: false
      suggestion: false
      delete_object: false
      assessment360: false
      review_files: true
      advertise_for_partners: true
      join_team_requests: true
      advertise_for_partner: true
      automated_metareviews: true
      advice: false
      analytic: false
      versions: true
      student_quiz: true
    pages:
      home: true
      expired: true
      notfound: true
      denied: true
      contact_us: true
      site_admin: false
      adminpage: false
      credits: true
      wiki: true
    permission_ids:
    - 8
    - 4
    - 3
    role_id: 1
    role_ids:
    - 1
    updated_at: 2015-06-11 15:23:43.000000000 Z
  :menu: !ruby/object:Menu
    by_id:
      1: &1 !ruby/object:Menu::Node
        content_page_id: 1
        controller_action_id:
        id: 1
        label: Home
        name: home
        parent:
        parent_id:
        site_controller_id:
        url: "/home"
      26: &2 !ruby/object:Menu::Node
        content_page_id:
        controller_action_id: 33
        id: 26
        label: Assignments
        name: student_task
        parent:
        parent_id:
        site_controller_id: 23
        url: "/student_task/list"
      27: &4 !ruby/object:Menu::Node
        content_page_id:
        controller_action_id: 36
        id: 27
        label: Profile
        name: profile
        parent:
        parent_id:
        site_controller_id: 26
        url: "/profile/edit"
      2: &5 !ruby/object:Menu::Node
        content_page_id: 6
        controller_action_id:
        id: 2
        label: Contact Us
        name: contact_us
        parent:
        parent_id:
        site_controller_id:
        url: "/contact_us"
        children:
        - 14
      14: &7 !ruby/object:Menu::Node
        content_page_id: 10
        controller_action_id:
        id: 14
        label: Credits &amp; Licence
        name: credits
        parent:
        parent_id: 2
        site_controller_id:
        url: "/credits"
      50: &24 !ruby/object:Menu::Node
        content_page_id:
        controller_action_id: 15
        id: 50
        label: Anonymized view
        name: anonymized_view
        parent:
        parent_id: 37
        site_controller_id: 35
        url: "/users/set_anonymized_view"
    by_name:
      home: *1
      student_task: *2
      profile: *4
      contact_us: *5
      credits: *7
      anonymized_view: *24
    crumbs:
    - 1
    root: &8 !ruby/object:Menu::Node
      parent:
      children:
      - 1
      - 26
      - 27
      - 2
      - 50
    selected:
      1: *1
    vector:
    - *8
    - *1