# be sure to restart your server when you modify this file...
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
development:
  secret_key_base:  03a719b6b452bd22e1f3d5933578203edb98c1235eeacd083ac503c4bddd1b2e392e588dc3f756180ef8071ccf26db14828d42ecf0a391df6139618b380c1403

test:
  secret_key_base:  d44b993d6800128ac07c2193b672b9b0f2b3679bd89e997a82fc739877af880130ae6785491d20e3e00bb8950b389d51ff7ae4c58a7d70acd6307761a7882587

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
